import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guide: [
    {
      type: 'category',
      label: '安装',
      link: {
        type: 'doc',
        id: 'install/index',
      },
      items: [
        {
          type: 'category',
          label: '本机安装',
          link: {
            type: 'doc',
            id: 'install/native',
          },
          items: ['install/llqqnt-airgap'],
        },
        'install/phone/index',
        'install/trusted-installation',
      ],
    },
    {
      type: 'category',
      label: '接入',
      link: {
        type: 'doc',
        id: 'connect/index',
      },
      items: [
        'connect/koishi',
        'connect/nonebot',
        'connect/avilla',
        'connect/kiramibot',
      ],
    },
    {
      type: 'category',
      label: '配置',
      link: {
        type: 'doc',
        id: 'config/index',
      },
      items: ['config/reference'],
    },
  ],
  developSatori: [
    'develop/satori/index',
    'develop/satori/quickstart',
    {
      type: 'category',
      label: '基础',
      link: {
        type: 'doc',
        id: 'develop/satori/fundamentals/index',
      },
      items: [
        'develop/satori/fundamentals/resources',
        'develop/satori/fundamentals/api',
        'develop/satori/fundamentals/events',
        'develop/satori/fundamentals/messages',
      ],
    },
    {
      type: 'category',
      label: '参考',
      link: {
        type: 'doc',
        id: 'develop/satori/reference/index',
      },
      items: [
        {
          type: 'link',
          label: 'API',
          href: '/develop/satori/reference/api',
        },
        'develop/satori/reference/elements/index',
      ],
    },
  ],
  faq: [
    {
      type: 'autogenerated',
      dirName: 'faq',
    },
  ],
  code: [
    {
      type: 'autogenerated',
      dirName: 'code',
    },
  ],
  more: [
    {
      type: 'autogenerated',
      dirName: 'more',
    },
  ],
}

export = sidebars
