import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guide: [
    {
      type: 'category',
      label: '安装 Chronocat',
      link: {
        type: 'doc',
        id: 'guide/install/shell/index',
      },
      items: [
        {
          type: 'category',
          label: '本机安装',
          link: {
            type: 'doc',
            id: 'guide/install/shell/native/index',
          },
          items: ['guide/install/shell/native/llqqnt-airgap'],
        },
        'guide/install/shell/phone/index',
        'guide/install/shell/trusted-installation',
      ],
    },
    {
      type: 'category',
      label: '安装引擎',
      link: {
        type: 'doc',
        id: 'guide/install/engine/index',
      },
      items: [
        'guide/install/engine/chronocat-api',
        'guide/install/engine/chronocat-event',
        'guide/install/engine/poke',
      ],
    },
    {
      type: 'category',
      label: '接入',
      link: {
        type: 'doc',
        id: 'guide/connect/index',
      },
      items: [
        'guide/connect/koishi',
        'guide/connect/nonebot',
        'guide/connect/avilla',
        'guide/connect/kiramibot',
      ],
    },
    {
      type: 'category',
      label: '配置',
      link: {
        type: 'doc',
        id: 'guide/config/index',
      },
      items: ['guide/config/reference'],
    },
  ],
  developSatori: [
    'develop/satori/index',
    'develop/satori/quickstart',
    {
      type: 'category',
      label: '基础',
      link: {
        type: 'doc',
        id: 'develop/satori/fundamentals/index',
      },
      items: [
        'develop/satori/fundamentals/resources',
        'develop/satori/fundamentals/api',
        'develop/satori/fundamentals/events',
        'develop/satori/fundamentals/messages',
      ],
    },
    {
      type: 'category',
      label: '参考',
      link: {
        type: 'doc',
        id: 'develop/satori/reference/index',
      },
      items: [
        {
          type: 'link',
          label: 'API',
          href: '/develop/satori/reference/api',
        },
        'develop/satori/reference/elements/index',
      ],
    },
  ],
  faq: [
    {
      type: 'autogenerated',
      dirName: 'faq',
    },
  ],
  code: [
    {
      type: 'autogenerated',
      dirName: 'code',
    },
  ],
  more: [
    {
      type: 'autogenerated',
      dirName: 'more',
    },
  ],
}

export = sidebars
